### GET request with a header
GET https://localhost:7104/WeatherForecast
Accept: application/json

### Send POST request with json body
POST https://examples.http-client.intellij.net/post
Content-Type: application/json

###
POST https://localhost:7104/api/auth/register
Content-Type: application/json

{
  "FirstName": "Jorge",
  "LastName": "& Mateus", 
  "Email": "t_ednei.silva@hapvida.com.br",
  "Password": "12345678"
}

###
POST https://localhost:7104/api/auth/login
Content-Type: application/json

{
  "Email": "silva@hapvida.com.br",
  "Password": "12345678"
}


