
# @env local
@BaseUrl=https://localhost:7104/api/v1

@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNTZlZTk1Yy1mZDhiLTQxYzktOTljNC03NjMxYTVkNjc4Y2EiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicGl0dGVyIiwiZmFtaWx5X25hbWUiOiJwaXR0ZXIgam9ncmUiLCJqdGkiOiI5MDkzNTQxNC04ZGUyLTQzYjEtODJiYi00ZmZjZDg1MTc4MjMiLCJlbWFpbCI6InBpdHRlcmpvcmdlMUBnbWFpbC5jb20iLCJpYXQiOjE3NjA2MzUzMDAsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJuYmYiOjE3NjA2MzUzMDMsImV4cCI6MTc2MDYzNzEwMCwiaXNzIjoiYnViZXJEaW5uZXIuY29tIiwiYXVkIjoiYnViZXJEaW5uZXIuY29tIn0.i4-nNbJVUlkJfKNLZK6Rtq_VXIMwCgbI2zo9MEy8eNU
GET {{BaseUrl}}/dinners/list/BDCD9E0C-7670-40D9-AADA-01DC0F7C0A21?onlyactives=false

Content-Type: application/json
Authorization: Bearer {{Token}}
