
# @env local
@BaseUrl=https://localhost:7104/api/v1
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTJjMWU5ZS1mNjM5LTQ1ZjctYjcyMS1lMDgwMjE0YzRmZTEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWF1cm8iLCJmYW1pbHlfbmFtZSI6IlBpdHRlciIsImp0aSI6ImM5YWYxZjljLTQyNjQtNGZmYi04NmY0LTdiZDJiZWI3YTgzYiIsImVtYWlsIjoiTWF1cm9QaXR0ZXJAZ21haWwuY29tIiwiaWF0IjoxNzYwMjM0NDY4LCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwibmJmIjoxNzYwMjM0NDcxLCJleHAiOjE3NjAyMzYyNjgsImlzcyI6ImJ1YmVyRGlubmVyLmNvbSIsImF1ZCI6ImJ1YmVyRGlubmVyLmNvbSJ9.vBIvqVyPc_fIifpjzF6tF1YOi_1X8qViRJU-tyYxIk8
GET {{BaseUrl}}/dinners/list/BDCD9E0C-7670-40D9-AADA-01DC0F7C0A21?onlyactives=false
Content-Type: application/json
Authorization: Bearer {{Token}}
