
@Host=https://localhost:7104/api/v1

POST {{Host}}/auth/register
Content-Type: application/json

{ 
  "firstName": "Mauro" ,
  "lastName": "Pitter",
  "email": "MauroPitter@gmail.com",
  "password": "crypto"
}  




