
@Host=https://localhost:7104/api/v1

POST {{HostAddress}}/auth/register
Content-Type: application/json

{ 
  "firstName": "Edy" ,
  "lastName": "Lopes",
  "email": "some1@gmail.com.br",
  "password": "cripyto"
}  



