@BaseUrl=https://localhost:7104/api/v1

@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTJjMWU5ZS1mNjM5LTQ1ZjctYjcyMS1lMDgwMjE0YzRmZTEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWF1cm8iLCJmYW1pbHlfbmFtZSI6IlBpdHRlciIsImp0aSI6ImI1NGM2YWE2LWE0ZDAtNDdmNi1hN2I5LTdhNDU0MzlmNzc1MSIsImVtYWlsIjoiTWF1cm9QaXR0ZXJAZ21haWwuY29tIiwiaWF0IjoxNzYwNjUwNDAyLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwibmJmIjoxNzYwNjUwNDA1LCJleHAiOjE3NjA2NTIyMDIsImlzcyI6ImJ1YmVyRGlubmVyLmNvbSIsImF1ZCI6ImJ1YmVyRGlubmVyLmNvbSJ9.Vh47vywURvM9W2PYuWMkelQAFJs_m-wtNnbrz1Wcsgk
GET {{BaseUrl}}/auth/me
Authorization: Bearer {{Token}}

