@BaseUrl=https://localhost:7104/api/v1

@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzQyNGMwNC0yMzU3LTQxMmQtYjllMS1iYjE3ZjlkMWQxN2QiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiRWR5IiwiZmFtaWx5X25hbWUiOiJsb3BlcyIsImp0aSI6ImZjMmM2MjlmLTMwZWMtNGFhNy1hNWU1LWE2YTNhZGI4MzJmMiIsImVtYWlsIjoic29tZW9uZTJAZ21haWwuY29tLmJyIiwiaWF0IjoxNzU5MzM5NTg5LCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwibmJmIjoxNzU5MzM5NTkyLCJleHAiOjE3NTkzNDEzODksImlzcyI6ImJ1YmVyRGlubmVyLmNvbSIsImF1ZCI6ImJ1YmVyRGlubmVyLmNvbSJ9.J6R4IW0-gAgt1WBsSYG8VVt-fLZKZZuiDCKVpt9KqRs

GET {{BaseUrl}}/auth/me
Authorization: Bearer {{Token}}

