# bloco de variáveis do RabbitMQ
x-rabbitmq-env: &rabbitmq-env
  environment:
    RabbitMqSettings__HostName: ${RabbitMqSettings__HostName}
    RabbitMqSettings__UserName: ${RabbitMqSettings__UserName}
    RabbitMqSettings__Password: ${RabbitMqSettings__Password}
    RabbitMqSettings__Port: ${RabbitMqSettings__Port}

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: buberdinner-sqlserver
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - buberdinner-network
    healthcheck:
      test: [ "CMD-SHELL", "pidof sqlservr || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: buberdinner-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - buberdinner-network
    env_file:
      - .env

  buberdinner.api:
    <<: *rabbitmq-env # merge do bloco RabbitMQ
    image: buberdinner.api
    container_name: buberdinner-api
    build:
      context: .
      dockerfile: BuberDinner.Api/Dockerfile
    env_file:
      - .env # lê SMTP e DB
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
      JwtSettings__SecretKey: ${JWT_SECRET}
      SmtpOptions__Host: ${SmtpOptions__Host}
      SmtpOptions__UserName: ${SmtpOptions__UserName}
      SmtpOptions__Password: ${SmtpOptions__Password}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - buberdinner-network

  buberdinner.worker:
    <<: *rabbitmq-env # merge do bloco RabbitMQ
    image: buberdinner.worker
    container_name: buberdinner-worker
    build:
      context: .
      dockerfile: BuberDinner.Worker/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      rabbitmq:
        condition: service_started
    networks:
      - buberdinner-network

volumes:
  sqlserver-data:
    driver: local

networks:
  buberdinner-network:
    driver: bridge
