### Send POST request with json body

POST https://localhost:7104/api/auth/register
Content-Type: application/json

{
  "FirstName": "Ednei",
  "LastName": "Lopes",
  "Email": "t_ednei.silva@hapvida.com.br",
  "Password": "hapvida"
}



