
### Send POST request with json body

@Host=http://localhost:7104/auth/api/v1
POST {{Host}}/auth/register
Content-Type: application/json

{
  "firstName": "Edy" ,
  "lastName": "Lopes",
  "email": "t_ednei.silva@hapvida.com.br",
  "password": "hapvida"
}



